server:
    port: 8080
spring:
  application:
    name: DisasterRecovery
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://summitworks.cjlwdcuayexf.us-east-1.rds.amazonaws.com:3306/DisasterCharts
    username: admin
    password: DoorOpen

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
summitworks:
  app:
    jwtSecret: summitworks
    jwtExpirationMs: 86400000
